language: csharp
mono: none
dotnet: 2.0.0

notifications:
  email: false

script:
  - cd SchoolSystem
  - dotnet restore
  - dotnet build
  - dotnet test SchoolSystem.Data.Tests/
  - dotnet test SchoolSystem.Services.Tests/
  - dotnet test SchoolSystem.Commands.Tests/
